j

diff --git a/misc/build b/misc/build
--- a/misc/build
+++ b/misc/build
@@ -1,36 +1,16 @@
 #!/bin/bash
+set -ue
 
-fatal_error() { printf "Error: %s\n" "$1" >&2 && exit 1; }
+error() { printf "Error: %s\n" "$1" >&2 && exit 1; }
 push_dir() { command pushd "$@" > /dev/null; }
 pop_dir() { command popd "$@" > /dev/null; }
 
-if [[ "$1" == "app" ]]; then
-  set -oue pipefail
-elif [[ "$1" == "tests" ]]; then
-  # IMPORTANT(Ryan): We cannot exit on error otherwise when tests fail, build will exit prematurely
-  set -u
-else
-  fatal_error "Usage: ./build <app|tests>\n"
-fi
+[[ "$1" != "app" && "$1" != "tests" ]] && error "Usage: ./build <app|tests>"
 
 BUILD_TYPE="$1"
 NAME="ui"
 
 BUILD_START_TIME=$(date +%s.%N)
-
-print_end_time() {
-  build_end_time=$(date +%s.%N)
-  build_time=$( echo "($build_end_time - $BUILD_START_TIME)" | bc -l )
-    
-  if [[ "$BUILD_TYPE" == "app" ]]; then 
-    printf "Build Time: %.4fs\n" "$build_time" 
-    printf "%.4f\n" "$build_time" >> misc/build-time.metric
-  else
-    printf "Build and Test Time: %.4fs\n" "$build_time" 
-  fi
-}
-# NOTE(Ryan): This will run even if build is interrupted
-# trap print_end_time EXIT
 
 shopt -s extglob
 CPU_INFO=$(lscpu)
@@ -38,31 +18,110 @@ parse_cpu_info() {
   local field_name="$1"
   local variable_name="$2"
 
-  field_value=$(echo "$CPU_INFO" | grep "$field_name" | cut -d ':' -f2)
+  field_value=$(echo "$CPU_INFO" | grep "^$field_name:" | cut -d ':' -f2)
   trimmed_value=${field_value##+([[:space:]])}
 
   eval "$variable_name=\"$trimmed_value\""
 }
 
-parse_cpu_info "Architecture" "arch"
-parse_cpu_info "Model name" "microarch"
-parse_cpu_info "CPU(s)" "cores"
-parse_cpu_info "CPU max MHz" "frequency"
-parse_cpu_info "Flags" "flags"
-simd=$(echo "$flags" | grep -o '\bavx\w*\b\|\bsse\w*\b')
-os_raw=$(lsb_release --description)
-os=${os_raw##+[[:space:]]}
+insert_metrics_db() {
+  local db_name="misc/$NAME-metrics.db"
+  [[ ! -f "$db_name" ]] && sqlite3 "$db_name" < "misc/metrics.sql"
 
+  parse_cpu_info "Architecture" "ARCH"
+  parse_cpu_info "Model name" "MICROARCH"
+  parse_cpu_info "CPU(s)" "CORES"
+  parse_cpu_info "CPU max MHz" "FREQUENCY"
+  parse_cpu_info "Flags" "FLAGS"
+  SIMD=$(echo "$FLAGS" | grep -o '\bavx\w*\b\|\bsse\w*\b')
+  OS_RAW=$(lsb_release --description | cut -d ':' -f2)
+  OS=${OS_RAW##+([[:space:]])}
 
-if [[ "$OSTYPE" == "linux-gnu" ]]; then
-  OS="linux"
-else
-  fatal_error "Build currently only supports linux\n"
-fi
+  local build_machine_str="${ARCH}${MICROARCH}${CORES}${FREQUENCY}${FLAGS}${SIMD}${OS}"
+  BUILD_MACHINE_HASH=$(echo -n "$build_machine_str" | sha256sum | awk '{print $1}')
+
+  local compiler_str="$($PARAM_COMPILER --version | head -1)"
+  local linker_str="$($PARAM_LINKER --version | head -1)"
+
+  local build_machine_str="
+insert into build_machines values 
+($BUILD_MACHINE_HASH,
+\"$OS\",
+\"$ARCH, $MICROARCH@$FREQUENCY ($CORES cores)\", 
+\"$compiler_str\", 
+\"$linker_str\");
+"
+
+  # NOTE(Ryan): Will error on duplicate build machine
+  echo "$build_machine_str" | sqlite3 -batch "$db_name" 
+
+  echo "GOT HERE 2"
+
+  local top10_symbols=$(nm -C --print-size --size-sort --reverse-sort --radix=d build/$BINARY_NAME | head -10)
+  local top10_symbols_str=""
+  while IFS= read -r line; do
+    read -r addr size type name <<< $(echo "$line")
+    top10_symbols_str+="\"${name}\",${size},"
+  done <<< "$top10_symbols"
+
+  local loc=0
+  for file in $(find -type f -iname "*.cpp" -o -iname "*.[ch]"); do
+    num_lines=$(cat "$file" | wc -l)
+    loc=$((loc + num_lines))
+  done
+
+  local sizes=$(size build/$BINARY_NAME | tail -1)
+  local text_size=$(sizes | cut -d ' ' -f1)
+  local data_size=$(sizes | cut -d ' ' -f2)
+  local bss_size=$(sizes | cut -d ' ' -f3)
+  local hash=$(git rev-parse HEAD)
+  local parent_hash=$(git rev-parse HEAD^@)
+
+  local metrics_str=""
+read -r -d '' metrics_str <<- EOV
+    with top10_id as (
+      insert into top10_symbols values
+      (default,
+       $top10_symbols_str)
+     returning id)
+    insert into build_metrics values 
+      (default, 
+       \"$NAME\",
+       \"$hash\"
+       \"$parent_hash\",
+       \"$BUILD_TYPE\",
+       $text_size,
+       $data_size,
+       $bss_size,
+       $BUILD_TIME,
+       $loc,
+       $BUILD_MACHINE_HASH,
+       (select id from top10_id)
+       );
+EOV
+
+  sqlite3 "$db_name" < "$metrics_str"
+}
+
+print_end_time() {
+  BUILD_END_TIME=$(date +%s.%N)
+  BUILD_TIME=$( echo "scale=4; ($BUILD_END_TIME - $BUILD_START_TIME)" | bc -l )
+    
+  if [[ "$BUILD_TYPE" == "app" ]]; then 
+    printf "Build Time: %.4fs\n" "$BUILD_TIME" 
+  else
+    printf "Build and Test Time: %.4fs\n" "$BUILD_TIME" 
+  fi
+}
+# NOTE(Ryan): This will run even if build is interrupted
+# trap print_end_time EXIT
+
+[[ "$OSTYPE" != "linux-gnu" ]] && error "Build currently only supports linux"
 
 # NOTE(Ryan): This file is ignored by source control to allow tweaking of build params without affecting history
 source "private/build-params"
 PARAM_COMPILER=${param_compiler:-"g++"}
+PARAM_LINKER=${param_linker:-"ld"}
 PARAM_MODE=${param_mode:-"debug"}
 PARAM_ARCH=${param_arch:-"x86_64"}
 PARAM_VERBOSE=${param_verbose:-"0"}
@@ -72,7 +131,7 @@ mkdir -p build run
 COMPILER_FLAGS=()
 LINKER_FLAGS=()
 
-if [[ "$PARAM_ARCH" == "x86_64" && "$PARAM_COMPILER" == "g++" && "$OS" == "linux" ]]; then
+if [[ "$PARAM_ARCH" == "x86_64" && "$PARAM_COMPILER" == "g++" && "$PARAM_LINKER" == "ld" && "$OSTYPE" == "linux-gnu" ]]; then
   # NOTE(Ryan): Enable various warnings largely related to implicit signed, alignment, casting, promotion issues
   COMPILER_FLAGS+=( "-Wall" "-Wextra" "-Wshadow" "-Wconversion" "-Wdouble-promotion" "-Wformat=2" "-pedantic" )
   COMPILER_FLAGS+=( "-Wundef" "-Wshadow" "-Wpadded" "-fno-common" "-march=native" )
@@ -109,7 +168,7 @@ if [[ "$PARAM_ARCH" == "x86_64" && "$PARAM_COMPILER" == "g++" && "$OS" == "linux
 
   LINKER_FLAGS+=( "-lm" "-ldl" "-lraylib" )
 
-  binary_name="$NAME-$PARAM_MODE"
+  BINARY_NAME="$NAME-$PARAM_MODE"
 
   if [[ "$PARAM_MODE" == "debug" ]]; then
     COMPILER_FLAGS+=( "-DDEBUG_BUILD" )
@@ -127,7 +186,7 @@ if [[ "$PARAM_ARCH" == "x86_64" && "$PARAM_COMPILER" == "g++" && "$OS" == "linux
     
     if [[ "$PARAM_VERBOSE" == "1" ]]; then
       # TODO(Ryan): Won't print compiler errors
-      compiler_output=$( { set -x; g++ "${COMPILER_FLAGS[@]}" "$app_name".cpp -o build/"$app_name" "${LINKER_FLAGS[@]}"; } 2>&1 )
+      compiler_output=$( { set -x; g++ "${COMPILER_FLAGS[@]}" "$NAME".cpp -o build/"$NAME" "${LINKER_FLAGS[@]}"; } 2>&1 )
 
       # NOTE(Ryan): Overcome Vim quickfix window line character limitation
       line_demarcation=900
@@ -144,15 +203,18 @@ if [[ "$PARAM_ARCH" == "x86_64" && "$PARAM_COMPILER" == "g++" && "$OS" == "linux
       second_line="${compiler_output:$((line_demarcation + 1))}"
       printf "%s\n%s\n" "$first_line" "$second_line"
     else
-      g++ ${COMPILER_FLAGS[*]} "$app_name".cpp -o build/"$binary_name" ${LINKER_FLAGS[*]}
+      g++ ${COMPILER_FLAGS[*]} "$NAME".cpp -o build/"$BINARY_NAME" ${LINKER_FLAGS[*]}
     fi
 
     #g++ ${COMPILER_FLAGS[*]} code/app.cpp -shared -fPIC -o run/app.so ${LINKER_FLAGS[*]}
 
     print_end_time
 
+    insert_metrics_db
+    exit 1
+
     # NOTE(Ryan): Remove ascii colour escape sequences for Vim quickfix window
-    time build/"$binary_name" | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"
+    time build/"$BINARY_NAME" | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"
   elif [[ "$PARAM_MODE" == "release" ]]; then
     COMPILER_FLAGS+=( "-DRELEASE_BUILD" )
     COMPILER_FLAGS+=( "-O3" )
@@ -164,15 +226,19 @@ if [[ "$PARAM_ARCH" == "x86_64" && "$PARAM_COMPILER" == "g++" && "$OS" == "linux
     COMPILER_FLAGS+=( "-fdevirtualize-at-ltrans" )
     LINKER_FLAGS+=( "-Wl,--gc-sections" )
 
-    g++ ${COMPILER_FLAGS[*]} "$app_name".cpp -o build/"$binary_name" ${LINKER_FLAGS[*]}
+    g++ ${COMPILER_FLAGS[*]} "$NAME".cpp -o build/"$BINARY_NAME" ${LINKER_FLAGS[*]}
 
     print_end_time
 
     # NOTE(Ryan): Remove ascii colour escape sequences for Vim quickfix window
-    time build/"$binary_name" | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"
+    time build/"$BINARY_NAME" | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"
   else
-    fatal_error "Build currently only supports debug and release modes\n"
+    error "Build currently only supports debug and release modes"
   fi
+
+  # TODO(Ryan): Only run on master branch
+  insert_metrics_db
+
 else
-  fatal_error "Build currently only supports x86_64 g++ on linux\n"
+  error "Build currently only supports x86_64 g++ on linux"
 fi
